[package]
name = "tracky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12", features = ["advanced", "lazy", "wgpu", "smol", "debug"] }
iced_graphics = "0.12"
rust-utils = { git = "https://github.com/sub07/rust-utils"}
rust-utils-macro = { git = "https://github.com/sub07/rust-utils" }
iter_tools = "0.15"
anyhow = "1"
cpal = "0.15"
audrey = "0.3"
ordinalizer = "0.1"
smol_str = "0.2"

[dev-dependencies]
approx = "0.5.1"
