[package]
name = "tracky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10", features = ["advanced", "lazy", "wgpu"]}
rust-utils = { git = "https://github.com/sub07/rust-utils" }
rust-utils-macro = { git = "https://github.com/sub07/rust-utils" }
iter_tools = "0.1"
anyhow = "1.0"
cpal = "0.15.0"
audrey = "0.3"
