[package]
name = "tracky"
version = "0.1.0"
edition = "2021"

[profile.release-with-debug]
inherits = "release"
debug = true

[[bin]]
name = "tracky"
path = "src/main.rs"
#path = "src/sound_test_main.rs" # Test some sound related stuff

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
inline_tweak = "1.0"
derive-new = "0.5"
cpal = "0.15.0"
audrey = "0.3"
anyhow = "1.0"
gnuplot = "0.0.37"
rust_utils = { git = "https://github.com/sub07/rust-utils" }
rust_utils_macro = { git = "https://github.com/sub07/rust-utils" }
tiny-skia = "0.8.3"
tiny-skia-path = "0.8.3"
fontdue = "0.7.2"
winit = "0.28"
softbuffer = { git = "https://github.com/sub07/softbuffer.git", branch = "owned-buffer" }
