on: push

jobs:
    validation:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Install linux deps
              run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev pkg-config
            - run: cargo test
    
    linter:
        name: Run rustfmt + clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: rustfmt, clippy
            - name: Install linux deps
              run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev pkg-config
            - name: Rustfmt Check
              uses: actions-rust-lang/rustfmt@v1
            - name: Clippy Check
              run: cargo clippy -- -D warnings